version: '2'

services:
  shopping_cart_rs:
    image: shopping_cart_rs
    ports:
      - "5000:5000"
  user_auth_rs:
    image: user_auth_rs
    ports:
      - "3000:3000"
    depends_on:
      - user_db
  email_service:
    image: email_service
    depends_on:
      - kafka
  storage_rs:
    image: storage_rs
    ports:
      - "4000:4000"
    depends_on:
      - storage_db
  storage_db:
    image: mongo
    volumes:
      - storage_db:/data/db
  user_db:
    image: mongo
    volumes:
      - user_db:/data/db
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=email_queue:1:1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

volumes:
  storage_db:
  user_db:
